name: Docker Test Build

env:
  app: fuxa
  version: test
  # for available platforms see output of a previous run -
  # ie the "Setup Docker BuildX" / "Inspect Builder" section
  # has eg "node_platforms": "linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  # but the platforms must also be included in the os image chosen -
  # eg the ubuntu image doesn't include linux/arm/v6.
  platforms: linux/amd64,linux/arm64,linux/arm/v7

on: workflow_dispatch

jobs:
  build-container:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU emulator
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.platforms }}
          tags: frangoteam/${{ env.app }}:${{ env.version }}
          outputs: type=oci,dest=/tmp/${{ env.app }}-${{ env.version }}.tar
          build-args: |
            REPO_URL=${{ github.server_url }}/${{ github.repository }}
            BRANCH_NAME=${{ github.head_ref || github.ref_name }}
            NODE_OPTIONS_ARG=--max-old-space-size=8192

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.app }}-docker-image-${{ env.version }}
          path: /tmp/${{ env.app }}-${{ env.version }}.tar
          retention-days: 7